config/routes.rb
Rails.application.routes.draw do

  root to: "games#index"
  resources :users
  resources :players
  resources :moves
  resources :games

end

app/models/move.rb
class Move < ActiveRecord::Base
  belongs_to :game

  validates :value, inclusion: { in: %w(o x) }

    validate :on_board, on: :create
    validate :empty_square, on: :create
    validate :own_turn, on: :create

    def on_board
      errors.add(:square, "Does not compute") unless (0..8).include? self.square
    end

    def vacant_square
      errors.add(:square, "Occupied, yo!") if Move.where(game_id: self.game_id).pluck(:square).include? self.square
    end

    def own_turn
      errors.add(:player_id, "I don't remember asking you a damn thing") unless self.player_id == Game.find(self.game_id).whose_turn
    end
end

app/controllers/moves_controller.rb
class MovesController < ApplicationController
  before_action :set_move, only: [:show, :edit, :update, :destroy]

  # GET /moves
  # GET /moves.json
  def index
    @moves = Move.all
  end

  # GET /moves/1
  # GET /moves/1.json
  def show
  end

  # GET /moves/new
  def new
    @move = Move.new
  end

  # GET /moves/1/edit
  def edit
  end

  # POST /moves
  # POST /moves.json
  def create
    @move = Move.new(move_params)

    respond_to do |format|
      if @move.save
        format.html { redirect_to @move, notice: 'Move was successfully created.' }
        format.json { render :show, status: :created, location: @move }
      else
        format.html { render :new }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /moves/1
  # PATCH/PUT /moves/1.json
  def update
    respond_to do |format|
      if @move.update(move_params)
        format.html { redirect_to @move, notice: 'Move was successfully updated.' }
        format.json { render :show, status: :ok, location: @move }
      else
        format.html { render :edit }
        format.json { render json: @move.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /moves/1
  # DELETE /moves/1.json
  def destroy
    @move.destroy
    respond_to do |format|
      format.html { redirect_to moves_url, notice: 'Move was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_move
      @move = Move.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def move_params
      params.require(:move).permit(:game_id, :player_id, :square, :symbol)
    end
end

app/helpers/moves_helper.rb
module MovesHelper
end

app/views/moves/_form.html.erb
<%= form_for(@move) do |f| %>
  <% if @move.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@move.errors.count, "error") %> prohibited this move from being saved:</h2>

      <ul>
      <% @move.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :game_id %><br>
    <%= f.number_field :game_id %>
  </div>
  <div class="field">
    <%= f.label :player_id %><br>
    <%= f.number_field :player_id %>
  </div>
  <div class="field">
    <%= f.label :square %><br>
    <%= f.number_field :square %>
  </div>
  <div class="field">
    <%= f.label :symbol %><br>
    <%= f.text_field :symbol %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/moves/edit.html.erb
<h1>Editing Move</h1>

<%= render 'form' %>

<%= link_to 'Show', @move %> |
<%= link_to 'Back', moves_path %>

app/views/moves/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Moves</h1>

<table>
  <thead>
    <tr>
      <th>Game</th>
      <th>Player</th>
      <th>Square</th>
      <th>Symbol</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @moves.each do |move| %>
      <tr>
        <td><%= move.game_id %></td>
        <td><%= move.player_id %></td>
        <td><%= move.square %></td>
        <td><%= move.symbol %></td>
        <td><%= link_to 'Show', move %></td>
        <td><%= link_to 'Edit', edit_move_path(move) %></td>
        <td><%= link_to 'Destroy', move, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Move', new_move_path %>

app/views/moves/new.html.erb
<h1>New Move</h1>

<%= render 'form' %>

<%= link_to 'Back', moves_path %>

app/views/moves/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Game:</strong>
  <%= @move.game_id %>
</p>

<p>
  <strong>Player:</strong>
  <%= @move.player_id %>
</p>

<p>
  <strong>Square:</strong>
  <%= @move.square %>
</p>

<p>
  <strong>Symbol:</strong>
  <%= @move.symbol %>
</p>

<%= link_to 'Edit', edit_move_path(@move) %> |
<%= link_to 'Back', moves_path %>